apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: proj-app
  name: proj-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proj-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: proj-app
    spec:
      containers:
      - image: 637423550581.dkr.ecr.ap-northeast-2.amazonaws.com/eks-repo:103
        name: proj
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

