apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: proj-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proj-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetCPUUtilizationPercentage: 50
