apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 31117
  selector:
    app: grafana


